import ROLES from "./roles.js";

const ADMIN_PERMISSIONS = Object.freeze({
  USERS_READ: "users.read",
  USERS_WRITE: "users.write",
  USERS_STATUS: "users.status",
  USERS_ROLE_ASSIGN: "users.role.assign",
  USERS_DEVICES_READ: "users.devices.read",
  USERS_LOGIN_HISTORY_READ: "users.login_history.read",
  USERS_GENERATIONS_READ: "users.generations.read",
  USERS_PAYMENTS_READ: "users.payments.read",
  USERS_SUBSCRIPTIONS_READ: "users.subscriptions.read",
  WALLETS_READ: "wallets.read",
  WALLETS_ADJUST: "wallets.adjust",
  WALLETS_REFUND: "wallets.refund",
  WALLETS_LOCK: "wallets.lock",
  WALLETS_TRANSACTIONS_READ: "wallets.transactions.read",
  TEMPLATES_READ: "templates.read",
  TEMPLATES_WRITE: "templates.write",
  TEMPLATES_PUBLISH: "templates.publish",
  CATEGORIES_READ: "categories.read",
  CATEGORIES_WRITE: "categories.write",
  PROVIDERS_READ: "providers.read",
  PROVIDERS_WRITE: "providers.write",
  PROVIDER_MODELS_READ: "provider_models.read",
  PROVIDER_MODELS_WRITE: "provider_models.write",
  PROVIDER_PRICING_WRITE: "providers.pricing.write",
  SUBSCRIPTIONS_READ: "subscriptions.read",
  SUBSCRIPTIONS_WRITE: "subscriptions.write",
  PAYMENTS_READ: "payments.read",
  PAYMENTS_REFUND: "payments.refund",
  PAYMENTS_TOKENS_READ: "payments.tokens.read",
  DASHBOARD_READ: "dashboard.read",
  SETTINGS_READ: "settings.read",
  SETTINGS_WRITE: "settings.write",
  COUPONS_READ: "coupons.read",
  COUPONS_WRITE: "coupons.write",
  REWARDS_READ: "rewards.read",
  NOTIFICATIONS_READ: "notifications.read",
  NOTIFICATIONS_WRITE: "notifications.write",
  AUDIT_LOGS_READ: "audit_logs.read",
  ANALYTICS_READ: "analytics.read",
  STORAGE_READ: "storage.read",
  GENERATION_READ: "generation.read",
  GENERATION_WRITE: "generation.write",
  ROLES_READ: "roles.read",
  ROLES_WRITE: "roles.write",
  PERMISSIONS_READ: "permissions.read",
});

const ADMIN_PERMISSION_DEFINITIONS = Object.freeze([
  {
    code: ADMIN_PERMISSIONS.USERS_READ,
    group: "users",
    label: "Read users",
    description: "View users and user detail.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_WRITE,
    group: "users",
    label: "Manage users",
    description: "Update user profile level admin fields.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_STATUS,
    group: "users",
    label: "Manage user status",
    description: "Suspend, block, or activate users.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_ROLE_ASSIGN,
    group: "users",
    label: "Assign user roles",
    description: "Assign platform admin roles.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_DEVICES_READ,
    group: "users",
    label: "Read devices",
    description: "View user devices.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_LOGIN_HISTORY_READ,
    group: "users",
    label: "Read login history",
    description: "View sessions and login history.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_GENERATIONS_READ,
    group: "users",
    label: "Read user generations",
    description: "View user generation history.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_PAYMENTS_READ,
    group: "users",
    label: "Read user payments",
    description: "View user payment history.",
  },
  {
    code: ADMIN_PERMISSIONS.USERS_SUBSCRIPTIONS_READ,
    group: "users",
    label: "Read user subscriptions",
    description: "View user subscription state and history.",
  },
  {
    code: ADMIN_PERMISSIONS.WALLETS_READ,
    group: "wallets",
    label: "Read wallets",
    description: "View wallet balances and wallet history.",
  },
  {
    code: ADMIN_PERMISSIONS.WALLETS_ADJUST,
    group: "wallets",
    label: "Adjust wallets",
    description: "Grant, deduct, or reset wallet balances.",
  },
  {
    code: ADMIN_PERMISSIONS.WALLETS_REFUND,
    group: "wallets",
    label: "Refund wallets",
    description: "Issue wallet refunds.",
  },
  {
    code: ADMIN_PERMISSIONS.WALLETS_LOCK,
    group: "wallets",
    label: "Lock wallets",
    description: "Lock or unlock wallet access.",
  },
  {
    code: ADMIN_PERMISSIONS.WALLETS_TRANSACTIONS_READ,
    group: "wallets",
    label: "Read wallet transactions",
    description: "Search wallet transactions.",
  },
  {
    code: ADMIN_PERMISSIONS.TEMPLATES_READ,
    group: "templates",
    label: "Read templates",
    description: "View templates.",
  },
  {
    code: ADMIN_PERMISSIONS.TEMPLATES_WRITE,
    group: "templates",
    label: "Manage templates",
    description: "Create, update, delete, or archive templates.",
  },
  {
    code: ADMIN_PERMISSIONS.TEMPLATES_PUBLISH,
    group: "templates",
    label: "Publish templates",
    description: "Publish, schedule, feature, or trend templates.",
  },
  {
    code: ADMIN_PERMISSIONS.CATEGORIES_READ,
    group: "categories",
    label: "Read categories",
    description: "View template categories.",
  },
  {
    code: ADMIN_PERMISSIONS.CATEGORIES_WRITE,
    group: "categories",
    label: "Manage categories",
    description: "Create and update categories.",
  },
  {
    code: ADMIN_PERMISSIONS.PROVIDERS_READ,
    group: "providers",
    label: "Read providers",
    description: "View providers and health.",
  },
  {
    code: ADMIN_PERMISSIONS.PROVIDERS_WRITE,
    group: "providers",
    label: "Manage providers",
    description: "Update provider operational settings.",
  },
  {
    code: ADMIN_PERMISSIONS.PROVIDER_MODELS_READ,
    group: "providers",
    label: "Read provider models",
    description: "View provider models.",
  },
  {
    code: ADMIN_PERMISSIONS.PROVIDER_MODELS_WRITE,
    group: "providers",
    label: "Manage provider models",
    description: "Update provider models.",
  },
  {
    code: ADMIN_PERMISSIONS.PROVIDER_PRICING_WRITE,
    group: "providers",
    label: "Manage provider pricing",
    description: "Update provider pricing.",
  },
  {
    code: ADMIN_PERMISSIONS.SUBSCRIPTIONS_READ,
    group: "subscriptions",
    label: "Read subscriptions",
    description: "View subscriptions.",
  },
  {
    code: ADMIN_PERMISSIONS.SUBSCRIPTIONS_WRITE,
    group: "subscriptions",
    label: "Manage subscriptions",
    description: "Cancel, renew, extend, or grant premium.",
  },
  {
    code: ADMIN_PERMISSIONS.PAYMENTS_READ,
    group: "payments",
    label: "Read payments",
    description: "View payments and revenue.",
  },
  {
    code: ADMIN_PERMISSIONS.PAYMENTS_REFUND,
    group: "payments",
    label: "Refund payments",
    description: "Refund platform payments.",
  },
  {
    code: ADMIN_PERMISSIONS.PAYMENTS_TOKENS_READ,
    group: "payments",
    label: "Read purchase tokens",
    description: "View Google purchase token metadata.",
  },
  {
    code: ADMIN_PERMISSIONS.DASHBOARD_READ,
    group: "dashboard",
    label: "Read dashboard",
    description: "View admin dashboard data.",
  },
  {
    code: ADMIN_PERMISSIONS.SETTINGS_READ,
    group: "settings",
    label: "Read settings",
    description: "View application settings.",
  },
  {
    code: ADMIN_PERMISSIONS.SETTINGS_WRITE,
    group: "settings",
    label: "Manage settings",
    description: "Update application settings.",
  },
  {
    code: ADMIN_PERMISSIONS.COUPONS_READ,
    group: "coupons",
    label: "Read coupons",
    description: "View coupons.",
  },
  {
    code: ADMIN_PERMISSIONS.COUPONS_WRITE,
    group: "coupons",
    label: "Manage coupons",
    description: "Create, update, and delete coupons.",
  },
  {
    code: ADMIN_PERMISSIONS.REWARDS_READ,
    group: "rewards",
    label: "Read rewards",
    description: "View reward history.",
  },
  {
    code: ADMIN_PERMISSIONS.NOTIFICATIONS_READ,
    group: "notifications",
    label: "Read notifications",
    description: "View notifications.",
  },
  {
    code: ADMIN_PERMISSIONS.NOTIFICATIONS_WRITE,
    group: "notifications",
    label: "Manage notifications",
    description: "Create admin notifications.",
  },
  {
    code: ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
    group: "audit",
    label: "Read audit logs",
    description: "View audit logs.",
  },
  {
    code: ADMIN_PERMISSIONS.ANALYTICS_READ,
    group: "analytics",
    label: "Read analytics",
    description: "View analytics and reports.",
  },
  {
    code: ADMIN_PERMISSIONS.STORAGE_READ,
    group: "storage",
    label: "Read storage",
    description: "View storage assets and usage.",
  },
  {
    code: ADMIN_PERMISSIONS.GENERATION_READ,
    group: "generation",
    label: "Read generation jobs",
    description: "View generation jobs.",
  },
  {
    code: ADMIN_PERMISSIONS.GENERATION_WRITE,
    group: "generation",
    label: "Manage generation jobs",
    description: "Update or cancel generation jobs.",
  },
  {
    code: ADMIN_PERMISSIONS.ROLES_READ,
    group: "roles",
    label: "Read roles",
    description: "View admin roles.",
  },
  {
    code: ADMIN_PERMISSIONS.ROLES_WRITE,
    group: "roles",
    label: "Manage roles",
    description: "Manage admin role configuration.",
  },
  {
    code: ADMIN_PERMISSIONS.PERMISSIONS_READ,
    group: "roles",
    label: "Read permissions",
    description: "View permission catalog.",
  },
]);

const DEFAULT_ADMIN_ROLE_CONFIGS = Object.freeze([
  {
    code: ROLES.SUPER_ADMIN,
    label: "Super Admin",
    description: "Full platform access across all admin resources.",
    isSystem: true,
    inherits: [],
    permissions: ["*"],
  },
  {
    code: ROLES.ADMIN,
    label: "Admin",
    description: "Full operational access except role superuser actions.",
    isSystem: true,
    inherits: [],
    permissions: [
      ADMIN_PERMISSIONS.USERS_READ,
      ADMIN_PERMISSIONS.USERS_WRITE,
      ADMIN_PERMISSIONS.USERS_STATUS,
      ADMIN_PERMISSIONS.USERS_ROLE_ASSIGN,
      ADMIN_PERMISSIONS.USERS_DEVICES_READ,
      ADMIN_PERMISSIONS.USERS_LOGIN_HISTORY_READ,
      ADMIN_PERMISSIONS.USERS_GENERATIONS_READ,
      ADMIN_PERMISSIONS.USERS_PAYMENTS_READ,
      ADMIN_PERMISSIONS.USERS_SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.WALLETS_READ,
      ADMIN_PERMISSIONS.WALLETS_ADJUST,
      ADMIN_PERMISSIONS.WALLETS_REFUND,
      ADMIN_PERMISSIONS.WALLETS_LOCK,
      ADMIN_PERMISSIONS.WALLETS_TRANSACTIONS_READ,
      ADMIN_PERMISSIONS.TEMPLATES_READ,
      ADMIN_PERMISSIONS.TEMPLATES_WRITE,
      ADMIN_PERMISSIONS.TEMPLATES_PUBLISH,
      ADMIN_PERMISSIONS.CATEGORIES_READ,
      ADMIN_PERMISSIONS.CATEGORIES_WRITE,
      ADMIN_PERMISSIONS.PROVIDERS_READ,
      ADMIN_PERMISSIONS.PROVIDERS_WRITE,
      ADMIN_PERMISSIONS.PROVIDER_MODELS_READ,
      ADMIN_PERMISSIONS.PROVIDER_MODELS_WRITE,
      ADMIN_PERMISSIONS.PROVIDER_PRICING_WRITE,
      ADMIN_PERMISSIONS.SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.SUBSCRIPTIONS_WRITE,
      ADMIN_PERMISSIONS.PAYMENTS_READ,
      ADMIN_PERMISSIONS.PAYMENTS_REFUND,
      ADMIN_PERMISSIONS.PAYMENTS_TOKENS_READ,
      ADMIN_PERMISSIONS.DASHBOARD_READ,
      ADMIN_PERMISSIONS.SETTINGS_READ,
      ADMIN_PERMISSIONS.SETTINGS_WRITE,
      ADMIN_PERMISSIONS.COUPONS_READ,
      ADMIN_PERMISSIONS.COUPONS_WRITE,
      ADMIN_PERMISSIONS.REWARDS_READ,
      ADMIN_PERMISSIONS.NOTIFICATIONS_READ,
      ADMIN_PERMISSIONS.NOTIFICATIONS_WRITE,
      ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
      ADMIN_PERMISSIONS.ANALYTICS_READ,
      ADMIN_PERMISSIONS.STORAGE_READ,
      ADMIN_PERMISSIONS.GENERATION_READ,
      ADMIN_PERMISSIONS.GENERATION_WRITE,
      ADMIN_PERMISSIONS.ROLES_READ,
      ADMIN_PERMISSIONS.PERMISSIONS_READ,
    ],
  },
  {
    code: ROLES.SUPPORT,
    label: "Support",
    description: "Support access for user resolution and account assistance.",
    isSystem: true,
    inherits: [],
    permissions: [
      ADMIN_PERMISSIONS.USERS_READ,
      ADMIN_PERMISSIONS.USERS_STATUS,
      ADMIN_PERMISSIONS.USERS_DEVICES_READ,
      ADMIN_PERMISSIONS.USERS_LOGIN_HISTORY_READ,
      ADMIN_PERMISSIONS.USERS_GENERATIONS_READ,
      ADMIN_PERMISSIONS.USERS_PAYMENTS_READ,
      ADMIN_PERMISSIONS.USERS_SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.WALLETS_READ,
      ADMIN_PERMISSIONS.WALLETS_ADJUST,
      ADMIN_PERMISSIONS.WALLETS_TRANSACTIONS_READ,
      ADMIN_PERMISSIONS.SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.PAYMENTS_READ,
      ADMIN_PERMISSIONS.NOTIFICATIONS_READ,
      ADMIN_PERMISSIONS.NOTIFICATIONS_WRITE,
      ADMIN_PERMISSIONS.DASHBOARD_READ,
      ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
    ],
  },
  {
    code: ROLES.MODERATOR,
    label: "Moderator",
    description: "Content moderation and template management access.",
    isSystem: true,
    inherits: [],
    permissions: [
      ADMIN_PERMISSIONS.USERS_READ,
      ADMIN_PERMISSIONS.TEMPLATES_READ,
      ADMIN_PERMISSIONS.TEMPLATES_WRITE,
      ADMIN_PERMISSIONS.TEMPLATES_PUBLISH,
      ADMIN_PERMISSIONS.CATEGORIES_READ,
      ADMIN_PERMISSIONS.CATEGORIES_WRITE,
      ADMIN_PERMISSIONS.NOTIFICATIONS_READ,
      ADMIN_PERMISSIONS.GENERATION_READ,
      ADMIN_PERMISSIONS.DASHBOARD_READ,
    ],
  },
  {
    code: ROLES.FINANCE,
    label: "Finance",
    description: "Payment and wallet administration access.",
    isSystem: true,
    inherits: [],
    permissions: [
      ADMIN_PERMISSIONS.WALLETS_READ,
      ADMIN_PERMISSIONS.WALLETS_ADJUST,
      ADMIN_PERMISSIONS.WALLETS_REFUND,
      ADMIN_PERMISSIONS.WALLETS_TRANSACTIONS_READ,
      ADMIN_PERMISSIONS.SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.PAYMENTS_READ,
      ADMIN_PERMISSIONS.PAYMENTS_REFUND,
      ADMIN_PERMISSIONS.PAYMENTS_TOKENS_READ,
      ADMIN_PERMISSIONS.REWARDS_READ,
      ADMIN_PERMISSIONS.DASHBOARD_READ,
      ADMIN_PERMISSIONS.ANALYTICS_READ,
      ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
    ],
  },
  {
    code: ROLES.ANALYTICS,
    label: "Analytics",
    description: "Read-only access to reports, audit, and operational metrics.",
    isSystem: true,
    inherits: [],
    permissions: [
      ADMIN_PERMISSIONS.DASHBOARD_READ,
      ADMIN_PERMISSIONS.ANALYTICS_READ,
      ADMIN_PERMISSIONS.PROVIDERS_READ,
      ADMIN_PERMISSIONS.SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.PAYMENTS_READ,
      ADMIN_PERMISSIONS.REWARDS_READ,
      ADMIN_PERMISSIONS.STORAGE_READ,
      ADMIN_PERMISSIONS.GENERATION_READ,
      ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
      ADMIN_PERMISSIONS.ROLES_READ,
      ADMIN_PERMISSIONS.PERMISSIONS_READ,
    ],
  },
  {
    code: ROLES.READ_ONLY,
    label: "Read Only",
    description: "Operational read-only access.",
    isSystem: true,
    inherits: [],
    permissions: [
      ADMIN_PERMISSIONS.USERS_READ,
      ADMIN_PERMISSIONS.USERS_DEVICES_READ,
      ADMIN_PERMISSIONS.USERS_LOGIN_HISTORY_READ,
      ADMIN_PERMISSIONS.USERS_GENERATIONS_READ,
      ADMIN_PERMISSIONS.USERS_PAYMENTS_READ,
      ADMIN_PERMISSIONS.USERS_SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.WALLETS_READ,
      ADMIN_PERMISSIONS.WALLETS_TRANSACTIONS_READ,
      ADMIN_PERMISSIONS.TEMPLATES_READ,
      ADMIN_PERMISSIONS.CATEGORIES_READ,
      ADMIN_PERMISSIONS.PROVIDERS_READ,
      ADMIN_PERMISSIONS.PROVIDER_MODELS_READ,
      ADMIN_PERMISSIONS.SUBSCRIPTIONS_READ,
      ADMIN_PERMISSIONS.PAYMENTS_READ,
      ADMIN_PERMISSIONS.COUPONS_READ,
      ADMIN_PERMISSIONS.REWARDS_READ,
      ADMIN_PERMISSIONS.NOTIFICATIONS_READ,
      ADMIN_PERMISSIONS.AUDIT_LOGS_READ,
      ADMIN_PERMISSIONS.DASHBOARD_READ,
      ADMIN_PERMISSIONS.SETTINGS_READ,
      ADMIN_PERMISSIONS.ANALYTICS_READ,
      ADMIN_PERMISSIONS.STORAGE_READ,
      ADMIN_PERMISSIONS.GENERATION_READ,
      ADMIN_PERMISSIONS.ROLES_READ,
      ADMIN_PERMISSIONS.PERMISSIONS_READ,
    ],
  },
]);

export default ADMIN_PERMISSIONS;
export { ADMIN_PERMISSION_DEFINITIONS, DEFAULT_ADMIN_ROLE_CONFIGS };
